apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ldml-api
  namespace: wstech
spec:
  ingressClassName: nginx
  rules:
    - host: ldml.api.languagetechnology.org
      http:
        paths:
          - backend:
              service:
                name: ldml-api
                port:
                  name: http
            path: /
            pathType: Prefix
