apiVersion: v1
kind: Service
metadata:
  name: ldml-api
  namespace: wstech
spec:
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-wstech-ldml-api
  type: ClusterIP
  ports:
  - name: http
    port: 80
