apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldml-api-data
  namespace: wstech
spec:
  #storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
