[package]
name = "ldml-api"
description = "LDML Rest API endpoint."
keywords = ["ldml", "http", "rest", "web"]
license = "GPLv3"
readme = "README.md"
version = "0.0.0"
authors = ["Tim Eves <tim_eves@sil.org>"]
edition = "2018"

[dependencies]
axum = { version = "0.4" }
nom = "5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "1.12" }
tokio = { version = "1.15", features= ["full"] }
tracing = "0.1"
tracing-subscriber = { version="0.3", features = ["env-filter"] }
tower-http = { version = "0.2.3", features = ["fs", "trace"] }