[global.ldml]
langtags = "../langtags/pub/"
sldr = "../sldr/"

[production]
sendfile_method = 'X-Accel-Redirect'

[production.ldml]
langtags = "/cms/sites/s/data/"
sldr = "/cms/sites/s/data/ldml-api/data/sldr/"

[production.ldml.staging]
langtags = "/cms/sites/s/data/staging/"
sldr = "/cms/sites/s/data/ldml-api/data/sldr-staging/"
