resources:
- ../prod
configMapGenerator: []
secretGenerator:
- name: ldml-api
  literals:
  - deploy-key=none 
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ldml-api-endpoint
  path: patch_image_pull.yaml
generatorOptions:
  disableNameSuffixHash: true
