apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-wstech-ldml-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-wstech-ldml-api
      namespace: wstech
    spec:
      serviceAccountName: api-deploy
      restartPolicy: Always
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
                - key: workload.user.cattle.io/workloadselector
                  operator: In
                  values:
                    - apps.deployment-wstech-ldml-api
      containers:
      - name: api-endpoint
        command:
          - ldml-api
          - '--listen=0.0.0.0:80'
          - '--config=/var/lib/ldml-api/config.json'
          - '--profile=production'
        env:
          - name: RUST_LOG
            value: ldml_api=trace,tower_http=trace,axum=trace
          - name: TOKIO_WORKER_THREADS
            value: '8'
        image: ghcr.io/tim-eves/ldml-api:latest
        livenessProbe:
          httpGet:
            path: /status
            port: http
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /status
            port: http
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        ports:
          - containerPort: 80
            name: http
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 128Mi
        volumeMounts:
          - mountPath: /var/lib/ldml-api/sldr
            name: data-sets
            readOnly: true
            subPath: sldr
          - mountPath: /var/lib/ldml-api/langtags
            name: data-sets
            readOnly: true
            subPath: langtags

      - name: deploy-endpoint
        image: debian:bookworm-slim
        resources:
          requests: &guarenteed
            memory: "256Mi" 
          limits: *guarenteed
        command: [sh, -ec]
        env:
        - { name: DEPLOY_KEY, valueFrom: { secretKeyRef: { name: ldml-api, key: deploy-key } } }
        - { name: DEPLOYMENT_NAME, value: ldml-api-endpoint }
        args:
        - >-
          apt-get update; apt-get install -y curl webhook; apt-get clean;
          exec webhook -verbose
          -urlprefix=hooks
          -template
          -x-request-id
          -hooks=/webhooks/hooks.yaml
        ports:
        - name: webhook
          containerPort: 9000
        volumeMounts:
        - name: webhooks
          mountPath: /webhooks
          readOnly: true

      initContainers:
      - name: update-langtags-db
        image: alpine/curl:8.12.1
        workingDir: /mnt/
        env:
        - name: STAGING_URL
          value: https://github.com/silnrsi/langtags/releases/download/staging/langtags.json
        - name: PRODUCTION_URL
          value: https://github.com/silnrsi/langtags/releases/latest/download/langtags.json
        command: [ '/bin/sh', '-ec' ]
        args:
        - >-
          mkdir -p langtags/staging; mkdir -p langtags/production; cd langtags; 
          curl --silent --location --etag-save staging/etag --etag-compare staging/etag ${STAGING_URL}
          --output staging/langtags.json;
          curl --silent --location --etag-save production/etag --etag-compare production/etag ${PRODUCTION_URL}
          --output production/langtags.json;
        resources:
          requests: &guarenteed
            memory: 64Mi
          limits: *guarenteed
        volumeMounts: 
        - mountPath: /mnt
          name: data-sets

      - name: update-sldr-data
        image: alpine/curl:8.12.1
        workingDir: /mnt/
        env:
        - name: STAGING_URL
          value: https://github.com/silnrsi/sldr/releases/download/staging/sldr.zip
        - name: PRODUCTION_URL
          value: https://github.com/silnrsi/sldr/releases/latest/download/sldr.zip
        command: [ '/bin/sh', '-ec' ]
        args:
        - >-
          mkdir -p sldr/staging; mkdir -p sldr/production; 
          cd sldr/staging; 
          curl --silent --location --etag-save etag --etag-compare etag ${STAGING_URL}
          | unzip -o - || true;
          cd ../production;
          curl --silent --location --etag-save etag --etag-compare etag ${PRODUCTION_URL}
          | unzip -o - || true;
        resources:
          requests:
            memory: 480Mi
          limits:
            memory: 512Mi
        volumeMounts: 
        - mountPath: /mnt
          name: data-sets

      volumes:
      - name: data-sets
        persistentVolumeClaim:
          claimName: data-sets
      - name: webhooks
        configMap:
          name: api
          items:
          - key: deploy.sh
            path: deploy.sh
            mode: 365
          - key: hooks.yaml
            path: hooks.yaml
