apiVersion: v1
kind: Service
metadata:
  name: api-endpoint
spec:
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-wstech-ldml-api
  type: ClusterIP
  ports:
  - name: http
    port: 80
  - name: webhook
    appProtocol: http
    port: 9000

