apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-sets
  namespace: wstech
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
