[package]
name = "language-tag"
description = "Language Tag type"
keywords = ["langtag", "web", "language", "metadata"]
license = "GPLv3"
readme = "README.md"
version = "0.2.0"
authors = ["Tim Eves <tim_eves@sil.org>"]
edition = "2021"

[lib]

[dependencies]
nom = "7"
serde_with = "3.0.0"